version: '3.9'
services:
  demo-node:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: demo-docker
    platform: linux/x86_64
    ports:
      - "3000:3000"
#   volumes:
#      - .:/home/source
#    working_dir: /home/source

networks:
  default:
    name: demo-net
