version: '3.9'
services:
  zalo-node:
    build:
      context: .
      dockerfile: Dockerfile.prod
#      target: production
    container_name: zalo-node
#    image: zalo-node:v1.0
    platform: linux/x86_64
    volumes:
      - .:/home/source
    environment:
      DB_HOST: 10.0.0.52
      DB_PORT: 30117
      DB_DATABASE: communicate_hub
      DB_USERNAME: root
      DB_PASSWORD: Adminscp@789@
#    working_dir: /home/source

networks:
  default:
    name: zalo-net
