name: demo-microservices

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/tailt9
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag demo-jenkins:$(date +%s)
